#!/bin/bash


# Check if the script is run as root
if [ "$(id -u)" != "0" ]; then
        clear
        echo 
        echo "!========================================================!"
        echo "- This operatiom must be run as root privligies. Exiting -"
        echo "!========================================================!"
        loading="./.loading"
        $loading
        echo
        sleep 1
        echo "!===== EXITING OPERATION =====!"
        sleep 1
        exit
fi


df -h


# quit
read -p "Do you want to return? (y/n): " choice

# Check the user's choice
if [ "$choice" == "y" ] || [ "$choice" == "Y" ]; then
    echo "Returning..."
    sleep 1
    exit 1
elif [ "$choice" == "n" ] || [ "$choice" == "N" ]; then
    echo "Returning anyway"
    sleep 1
    exit 1
else
    echo "Invalid choice. returning..."
    sleep 1
    exit 1
fi
